name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
          changelog-types: |
            [
              {"type":"feat","section":"Features"},
              {"type":"fix","section":"Bug Fixes"},
              {"type":"chore","section":"Chores"},
              {"type":"docs","section":"Documentation"},
              {"type":"refactor","section":"Refactoring"},
              {"type":"perf","section":"Performance"},
              {"type":"test","section":"Tests"}
            ] 